var root=document.getElementById('main');
var div1=document.createElement('div');
div1.classList.add('card');
root.appendChild(div1);
var image=document.createElement('img');
image.src="hii.png";
image.alt="profile picture";
image.classList.add('img');
div1.appendChild(image);
var heading=document.createElement("h2");
heading.textContent="Thanuja";
div1.appendChild(heading);
var para=document.createElement('h3');
para.textContent="Student";
div1.appendChild(para);
var para1=document.createElement('h3');
para.textContent="Thanuja@gmail.com";
div1.appendChild(para1);
var para2=document.createElement('h3');
para.textContent="123985435";
div1.appendChild(para2);
var anc=document.createElement('a');
anc.href="t1.html";
anc.textContent="viewprofile";
div1.classList.add("a");
div1.appendChild(anc);
// -----------------------
var div2=document.createElement('div');
div2.classList.add("card");
root.appendChild(div2);
var image=document.createElement('img');
image.src="hii.png";
image.alt="profile picture";
image.classList.add('img');
div2.appendChild(image);
var heading=document.createElement("h2");
heading.textContent="asritha";
div2.appendChild(heading);
var para=document.createElement('h3');
para.textContent="Student";
div2.appendChild(para);
var para1=document.createElement('h3');
para.textContent="aasi@gmail.com";
div2.appendChild(para1);
var para2=document.createElement('h3');
para.textContent="826985435";
div2.appendChild(para2);
var anc=document.createElement('a');
anc.href="t1.html";
anc.textContent="viewprofile";
div2.classList.add("a");
div2.appendChild(anc);
// ------------------
var div3=document.createElement('div');
div3.classList.add("card");
root.appendChild(div3);
var image=document.createElement('img');
image.src="hii.png";
image.alt="profile picture";
image.classList.add('img');
div3.appendChild(image);
var heading=document.createElement("h2");
heading.textContent="tejaswi";
div3.appendChild(heading);
var para=document.createElement('h3');
para.textContent="Student";
div3.appendChild(para);
var para1=document.createElement('h3');
para.textContent="teja@gmail.com";
div3.appendChild(para1);
var para2=document.createElement('h3');
para.textContent="876985435";
div3.appendChild(para2);
var anc=document.createElement('a');
anc.href="t1.html";
anc.textContent="viewprofile";
div3.classList.add("a");
div3.appendChild(anc);